name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Set up PHP
      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
        tools: phpcs # use for PHP_CodeSniffer-based linit test
        
    - name: Check out code
      uses: actions/checkout@v3
    
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Install Dependencies
      uses: php-actions/composer@v6
      with:
        php_version: "8.1"
        arg: "update -q --no-scripts"
      
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: |
        sudo chmod -R 775 storage bootstrap/cache
        sudo chown -R $USER:$USER storage bootstrap/cache

    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
        
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit

    - name: Install Behat and Mink
      run: |
        # composer require --dev behat/behat behat/mink behat/mink-extension --with-all-dependencies
        # composer require --dev friends-of-behat/mink-selenium2-driver --with-all-dependencies
        # composer update
        composer install
        composer require --dev behat/behat

    - name: Run Linter
      uses: wearerequired/lint-action@v2
      with:
        php_codesniffer: true
        # # Optional: Ignore warnings
        php_codesniffer_args: "-n" 
        auto_fix: true
